import { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";


export const metadata = {
  title: "Read The Blog",
  description: "Generated by create next app",
};

export default function LoginLayout({ children }) {
  return (
      <div>
      	{children}
      </div>
  )
}
