import { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import 'highlight.js/styles/xt256.min.css'


export const metadata = {
  title: "Read The Blog",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
     <div>{children}</div>
  )
}
